
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from mGrabaciones import grabar_audio_dir
from pruebaAudiosTest import predict_audio
import os


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"D:\Documentos\ESCOM\RECONOCIMIENTO DE VOZ\interfaz hp\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def grabar_audio():
    audio_file = grabar_audio_dir("pruebas_audios")
    hechizo = predict_audio(audio_file)
    # Mostrar el hechizo detectado en el campo de texto
    canvas.delete("hechizo")
    canvas.create_text(
        304.0,
        570.0,
        anchor="nw",
        text=f"Tu hechizo es: {hechizo}",
        fill="#FFFFFF",
        font=("CrimsonText Regular", 32 * -1),
        tags="hechizo"
    )


window = Tk()

window.geometry("1032x648")
window.configure(bg = "#17181C")


canvas = Canvas(
    window,
    bg = "#17181C",
    height = 648,
    width = 1032,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    49.0,
    46.0,
    anchor="nw",
    text="Modelo de reconocimiento de voz para\nclasificación de hechizos de Harry Potter",
    fill="#ECEEBC",
    font=("KaiseiHarunoUmi Regular", 40 * -1)
)

canvas.create_text(
    351.0,
    449.0,
    anchor="nw",
    text="Presiona el botón para iniciar la\ngrabación.",
    fill="#FFFFFF",
    font=("CrimsonText Regular", 20 * -1)
)

canvas.create_text(
    62.0,
    217.0,
    anchor="nw",
    text="¡Explora la magia de Harry Potter con nuestra interfaz interactiva de \nreconocimiento de voz! Graba tus propios hechizos y observa cómo nuestro\n sistema los clasifica al instante.\n",
    fill="#FFFFFF",
    font=("CrimsonText Regular", 24 * -1)
)

canvas.create_rectangle(
    -4.0,
    174.9999996508417,
    1032.0,
    179.00009155273438,
    fill="#8D815B",
    outline="")

canvas.create_rectangle(
    814.0,
    323.0,
    970.0,
    542.0,
    fill="#263B46",
    outline="")

canvas.create_text(
    833.0,
    335.0,
    anchor="nw",
    text="Hechizos \ndisponibles:\n\nCrucio\nDesmayo\nImperio\nLumos\nProtego\nReducto",
    fill="#FFFFFF",
    font=("CrimsonText Regular", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: grabar_audio(),
    relief="flat"
)
button_1.place(
    x=453.0,
    y=335.0,
    width=96.85920715332031,
    height=94.92422485351562
)

canvas.create_rectangle(
    261.0,
    542.0,
    742.0,
    625.0,
    fill="#5A5133",
    outline="")

canvas.create_text(
    304.0,
    570.0,
    anchor="nw",
    text="Aqui verás tu hechizo...",
    fill="#FFFFFF",
    font=("CrimsonText Regular", 32 * -1),
    tags="hechizo"
)
window.resizable(False, False)
window.mainloop()
